steps:

- id: 'Testes'
  name: "gcr.io/cloud-builders/go"
  args: ["test"]
  env: ["GOPATH=."]

- id: 'Build images'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/soma:0.0.1', '-t', 'gcr.io/$PROJECT_ID/soma:latest', '.']
  
images:
- 'gcr.io/$PROJECT_ID/soma:latest'
- 'gcr.io/$PROJECT_ID/soma:0.0.1'