steps:

- id: 'Teste soma'
  name: "gcr.io/cloud-builders/go"
  args: ["test","soma"]
  env: ["GOPATH=."]

- id: 'go_linter'
  name: "golangci/golangci-lint"
  args: ["golangci-lint","run"]

- id: 'Build images'
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg'
  - 'VERSION=0.0.1'
  - '-t'
  - 'gcr.io/$PROJECT_ID/soma:latest'
  - '-t'
  - 'gcr.io/$PROJECT_ID/soma:0.0.1'
  - '.'

- id: 'Tag'
  name: 'gcr.io/$PROJECT_ID/soma'
  args: ['version']

images:
- 'gcr.io/$PROJECT_ID/soma:latest'
- 'gcr.io/$PROJECT_ID/soma:0.0.1'
tags: ['0.0.1']